---
- name: install jenkins
  hosts: jenkins
  tasks:
  - name: Download jenkins repository file
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/rpm-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Install java-21 and fontconfig packages
    ansible.builtin.dnf:
      name: {{ item }}
      state: present
    loop:
      - java-21-openjdk
      - fontconfig
  - name: Install jenkins
    ansible.builtin.dnf:
      name: jenkins
      state: present
  - name: Enable and start jenkins service
    ansible.builtin.systemd_service:
      name: jenkins
      state: started
      enabled: true